import inputs
import sourceline

public class Assembler_Application{

	int LOCCTR = 0;

//array_of_sourcelines instantiated by int count = input.count(file )
//SourceLines[] array_of_sourcelines =  new SourceLines[count];
//array_of_sourcelines = generated by input.evaluate(array_of_sourcelines, file)
//


passone()//will gather location_address 
{	
	
}
addresses_without_issue()
{
	for each SourceLine in array_of_sourcelines
	{
		LOCCTR = SourceLine.getAddr(LOCCTR)//LOCCTR,SYMBOL,MNEMONIC,LABEL  
		SourceLine.update(LOCCTR)
	}
}

