import java.io.IOException;
import java.util.Scanner;
//import input.*;
//import Assembler_Application
public class Assembler_Application{
int LOCCTR = 0;

	public static void main(String [] args) throws IOException{ 
		input dragon = new input("output.txt");
		System.out.println();
		System.out.println();
		System.out.println("on to the second file.");
		input other_dragon = new input("output3.txt");
		source_line frog = new source_line("output.txt");
	}
//array_of_sourcelines instantiated by int count = input.count(file )
//SourceLines[] array_of_sourcelines =  new SourceLines[count];
//array_of_sourcelines = generated by input.evaluate(array_of_sourcelines, file)
//passone()//will gather location_address
//{
//
//}
//addresses_without_issue()
//{
//	for each SourceLine in array_of_sourcelines
//	{
//		LOCCTR = SourceLine.getAddr(LOCCTR)//LOCCTR,SYMBOL,MNEMONIC,LABEL
//		SourceLine.update(LOCCTR)
//	}
//}
}
